# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mini3.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mini3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmini3.proto\x12\x05mini3\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x08PeerInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0c\n\x04hops\x18\x03 \x01(\x05\"L\n\tHeartbeat\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x10\n\x08my_score\x18\x02 \x01(\x01\x12\x1f\n\x06gossip\x18\x03 \x03(\x0b\x32\x0f.mini3.PeerInfo\"A\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x10\n\x08reply_to\x18\x03 \x01(\t\"/\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\x80\x01\n\x0cMini3Service\x12\x39\n\rSendHeartbeat\x12\x10.mini3.Heartbeat\x1a\x16.google.protobuf.Empty\x12\x35\n\nSubmitTask\x12\x12.mini3.TaskRequest\x1a\x13.mini3.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mini3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEERINFO']._serialized_start=51
  _globals['_PEERINFO']._serialized_end=107
  _globals['_HEARTBEAT']._serialized_start=109
  _globals['_HEARTBEAT']._serialized_end=185
  _globals['_TASKREQUEST']._serialized_start=187
  _globals['_TASKREQUEST']._serialized_end=252
  _globals['_TASKRESPONSE']._serialized_start=254
  _globals['_TASKRESPONSE']._serialized_end=301
  _globals['_MINI3SERVICE']._serialized_start=304
  _globals['_MINI3SERVICE']._serialized_end=432
# @@protoc_insertion_point(module_scope)
